package Glot.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MethodType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MethodType() {
    super(0x28e4957b85994380L, 0x9a2de36d611c13b9L, 0x34b196dfcc949e1bL, "MethodType", "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/3796981848804204059");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_POST_0 = new EnumerationDescriptor.MemberDescriptor("POST", "POST", 0x34b196dfcc949e1cL, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/3796981848804204060");
  private final EnumerationDescriptor.MemberDescriptor myMember_GET_0 = new EnumerationDescriptor.MemberDescriptor("GET", "GET", 0x34b196dfcc949e1dL, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/3796981848804204061");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x28e4957b85994380L, 0x9a2de36d611c13b9L, 0x34b196dfcc949e1bL, 0x34b196dfcc949e1cL, 0x34b196dfcc949e1dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_POST_0, myMember_GET_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "POST":
        return myMember_POST_0;
      case "GET":
        return myMember_GET_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
