package Glot.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DataType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DataType() {
    super(0x28e4957b85994380L, 0x9a2de36d611c13b9L, 0x1f05a1bb5d897c33L, "DataType", "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/2235370616159566899");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_int_0 = new EnumerationDescriptor.MemberDescriptor("int", "int", 0x1f05a1bb5d897c34L, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/2235370616159566900");
  private final EnumerationDescriptor.MemberDescriptor myMember_string_0 = new EnumerationDescriptor.MemberDescriptor("string", "string", 0x1f05a1bb5d897c35L, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/2235370616159566901");
  private final EnumerationDescriptor.MemberDescriptor myMember_text_0 = new EnumerationDescriptor.MemberDescriptor("text", "text", 0x1f05a1bb5d897c38L, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/2235370616159566904");
  private final EnumerationDescriptor.MemberDescriptor myMember_bool_0 = new EnumerationDescriptor.MemberDescriptor("bool", "bool", 0x1f05a1bb5d897c3cL, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/2235370616159566908");
  private final EnumerationDescriptor.MemberDescriptor myMember_date_0 = new EnumerationDescriptor.MemberDescriptor("date", "date", 0x1f05a1bb5d8a2576L, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/2235370616159610230");
  private final EnumerationDescriptor.MemberDescriptor myMember_file_0 = new EnumerationDescriptor.MemberDescriptor("file", "file", 0x1f05a1bb5d8a257eL, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/2235370616159610238");
  private final EnumerationDescriptor.MemberDescriptor myMember_currency_0 = new EnumerationDescriptor.MemberDescriptor("currency", "currency", 0x3990f699fa62e790L, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/4148086397999441808");
  private final EnumerationDescriptor.MemberDescriptor myMember_percent_0 = new EnumerationDescriptor.MemberDescriptor("percent", "percent", 0x3990f699fa6fa89cL, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/4148086398000277660");
  private final EnumerationDescriptor.MemberDescriptor myMember_image_0 = new EnumerationDescriptor.MemberDescriptor("image", "image", 0x3990f699fa703701L, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/4148086398000314113");
  private final EnumerationDescriptor.MemberDescriptor myMember_images_0 = new EnumerationDescriptor.MemberDescriptor("images", "images", 0x3990f699fa70371fL, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/4148086398000314143");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x28e4957b85994380L, 0x9a2de36d611c13b9L, 0x1f05a1bb5d897c33L, 0x1f05a1bb5d897c34L, 0x1f05a1bb5d897c35L, 0x1f05a1bb5d897c38L, 0x1f05a1bb5d897c3cL, 0x1f05a1bb5d8a2576L, 0x1f05a1bb5d8a257eL, 0x3990f699fa62e790L, 0x3990f699fa6fa89cL, 0x3990f699fa703701L, 0x3990f699fa70371fL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_int_0, myMember_string_0, myMember_text_0, myMember_bool_0, myMember_date_0, myMember_file_0, myMember_currency_0, myMember_percent_0, myMember_image_0, myMember_images_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_string_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "int":
        return myMember_int_0;
      case "string":
        return myMember_string_0;
      case "text":
        return myMember_text_0;
      case "bool":
        return myMember_bool_0;
      case "date":
        return myMember_date_0;
      case "file":
        return myMember_file_0;
      case "currency":
        return myMember_currency_0;
      case "percent":
        return myMember_percent_0;
      case "image":
        return myMember_image_0;
      case "images":
        return myMember_images_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
