package Glot.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Attribute_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL) + " ");
    switch (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.type$U2Su))) {
      case "currency":
      case "int":
        tgs.append("INT");
        break;
      case "string":
        tgs.append("VARCHAR(255)");
        break;
      case "bool":
        tgs.append("BIT");
        break;
      case "text":
        tgs.append("TEXT");
        break;
      default:
        tgs.append("unknown");
        break;
    }
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.isPrimaryKey$8T7e)) {
      if (SEnumOperations.getMemberName0(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.type$U2Su)) == "int") {
        tgs.append(" UNSIGNED AUTO_INCREMENT");

      }
      tgs.append(" PRIMARY KEY");
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty type$U2Su = MetaAdapterFactory.getProperty(0x28e4957b85994380L, 0x9a2de36d611c13b9L, 0x1f05a1bb5d897c30L, 0x1f05a1bb5d897c31L, "type");
    /*package*/ static final SProperty isPrimaryKey$8T7e = MetaAdapterFactory.getProperty(0x28e4957b85994380L, 0x9a2de36d611c13b9L, 0x1f05a1bb5d897c30L, 0x6c21e3da475f0862L, "isPrimaryKey");
  }
}
