package Glot.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Element_Constraints extends BaseConstraintsDescriptor {
  public Element_Constraints() {
    super(CONCEPTS.Element$vg);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Element$vg = MetaAdapterFactory.getConcept(0x28e4957b85994380L, 0x9a2de36d611c13b9L, 0x34b196dfcc949dc3L, "Glot.structure.Element");
  }
}
